export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const ORDERS_LIST_MORE_REQUEST = 'ORDERS_LIST_MORE_REQUEST';
export const ORDERS_LIST_MORE_SUCCESS = 'ORDERS_LIST_MORE_SUCCESS';
export const ORDER_LIST_FILTER = 'ORDER_LIST_FILTER';
export const RESET_ORDERS = 'RESET_ORDERS';
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_SCHEME_REQUEST = 'ORDER_SCHEME_REQUEST';
export const ORDER_SCHEME_SUCCESS = 'ORDER_SCHEME_SUCCESS';

export const GET_CAPTCHA = 'GET_CAPTCHA';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const LOGOUT = 'LOGOUT';
export const SCHEME_CONFIRM_CHANGE_ACCOUNT = 'SCHEME_CONFIRM_CHANGE_ACCOUNT';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const NEW_REGISTER = 'NEW_REGISTER';
export const USER_INFO = 'USER_INFO';
export const IDCARD = 'IDCARD';
export const SET_IDCARD = 'SET_IDCARD';
export const GET_USER_BANKCARD = 'GET_USER_BANKCARD';
export const SET_USER_BANKCARD = 'SET_USER_BANKCARD';
export const GET_BANKS_LIST = 'GET_BANKS_LIST';
export const CASH = 'CASH';
export const CASHDETAIL = 'CASHDETAIL';
export const WITH_DRAW_CASH = 'WITH_DRAW_CASH';

export const BASE_REGISTER = 'BASE_REGISTER';
export const BASE_LOGIN = 'BASE_LOGIN';

export const MINE_INFO = 'MINE_INFO';
