export const GET_PRIZE_LIST = 'GET_PRIZE_LIST';
export const GET_PRIZE_DETAIL_LIST = 'GET_PRIZE_DETAIL_LIST';
export const GET_PRIZE_SPORTS_DETAIL = 'GET_PRIZE_SPORTS_DETAIL';
export const PRIZE_DETAIL_LIST_MORE = 'PRIZE_DETAIL_LIST_MORE';
export const PRIZE_DETAIL_LIST_RESET = 'PRIZE_DETAIL_LIST_RESET';
export const PRIZE_SPORT_DATE_SELECT = 'PRIZE_SPORT_DATE_SELECT';
export const PRIZE_SPORT_RESET = 'PRIZE_SPORT_RESET';
