export const GET_BANNER = 'GET_BANNER';
export const GET_RECOMMEND_ISSUE = 'GET_RECOMMEND_ISSUE';
export const GET_LOTTERY_LIST = 'GET_LOTTERY_LIST';
export const GET_INFORMATION_LIST = 'GET_INFORMATION_LIST';
export const LOTTERY_LIST_REFRESH = 'LOTTERY_LIST_REFRESH';
export const RECOMMEND_ISSUE_REFRESH = 'RECOMMEND_ISSUE_REFRESH';
export const CURRENT_LOTTERY_REFRESH = 'CURRENT_LOTTERY_REFRESH'
export const GO_RECOMMEND_LOTTERY = 'GO_RECOMMEND_LOTTERY';
