export const CURRENT_PLAY_TYPE_SELECT = 'CURRENT_PLAY_TYPE_SELECT';
export const SPORT_MODE_SELECT = 'SPORT_MODE_SELECT';
export const SET_CURRENT_LOTTERY = 'SET_CURRENT_LOTTERY';
export const CLEAR_BETTING_SELECTED = 'CLEAR_BETTING_SELECTED';
export const RANDOM_SELECTED_BALL = 'RANDOM_SELECTED_BALL';
export const GET_CURRENT_LOTTERY = 'GET_CURRENT_LOTTERY';
export const CURRENT_LOTTERY_REFRESH = 'CURRENT_LOTTERY_REFRESH';
export const RECOMMEND_ISSUE_SET = 'RECOMMEND_ISSUE_SET';
// 竞彩
export const GET_CURRENT_SPORT_LOTTERY = 'GET_CURRENT_SPORT_LOTTERY';
export const CURRENT_SPORT_PLAY_TYPE_SELECT = 'CURRENT_SPORT_PLAY_TYPE_SELECT';
export const SPORTS_OPTION_SELECTED = 'SPORTS_OPTION_SELECTED';
export const CLEAR_SPORT_BETTING_SELECTED = 'CLEAR_SPORT_BETTING_SELECTED';
export const SPORTS_CONFIRM_BET = 'SPORTS_CONFIRM_BET';
export const SPORTS_CONFIRM_DELETE_TICKET = 'SPORTS_CONFIRM_DELETE_TICKET';
export const SPORTS_CONFIRM_CLEAR_TICKETS = 'SPORTS_CONFIRM_CLEAR_TICKETS';
export const SPORTS_MULTIPLE_CHANGE = 'SPORTS_MULTIPLE_CHANGE';
export const SPORTS_CONFIRM_PAYMENT = 'SPORTS_CONFIRM_PAYMENT';
export const SPORTS_BONUS_CHANGE = 'SPORTS_BONUS_CHANGE';
export const SPORTS_FILTER_PANEL_CHANGE = 'SPORTS_FILTER_PANEL_CHANGE';

export const CONFIRM_BET = 'CONFIRM_BET';
export const CONFIRM_DELETE_TICKET = 'CONFIRM_DELETE_TICKET';
export const CONFIRM_CLEAR_TICKETS = 'CONFIRM_CLEAR_TICKETS';
export const FOLLOW_TIMES_CHANGE = 'FOLLOW_TIMES_CHANGE';
export const MULTIPLE_CHANGE = 'MULTIPLE_CHANGE';
export const CONFIRM_RANDOM_TICKET = 'CONFIRM_RANDOM_TICKET';
export const CLEAR_CONFIRM_BETTING_LIST = 'CLEAR_CONFIRM_BETTING_LIST';
export const DIGITAL_CONFIRM_PAYMENT = 'DIGITAL_CONFIRM_PAYMENT';
export const SPORTS_CONFIRM_SERIES_SET = 'SPORTS_CONFIRM_SERIES_SET';
export const SPORTS_CONFIRM_SERIES_CLEAR = 'SPORTS_CONFIRM_SERIES_CLEAR';

export const SPORTS_CONFIRM_OPTIMIZE = 'SPORTS_CONFIRM_OPTIMIZE';
export const SPORTS_OPTIMIZE_STAKE_CHANGE = 'SPORTS_OPTIMIZE_STAKE_CHANGE';
export const SPORTS_OPTIMIZE_ITEM_MONEY = 'SPORTS_OPTIMIZE_ITEM_MONEY';
export const SPORTS_OPTIMIZE_ITEM_CHECKED = 'SPORTS_OPTIMIZE_ITEM_CHECKED';
export const SPORTS_OPTIMIZE_CALCULATE = 'SPORTS_OPTIMIZE_CALCULATE';
export const SPORTS_OPTIMIZE_REDISTRIBUTION = 'SPORTS_OPTIMIZE_REDISTRIBUTION';
export const SPORTS_OPTIMIZE_INPUT_VALUE = 'SPORTS_OPTIMIZE_INPUT_VALUE';
export const SPORTS_OPTIMIZE_STAKE_DISTRIBUTION = 'SPORTS_OPTIMIZE_STAKE_DISTRIBUTION';

// 胜负彩
export const GET_CURRENT_SFC_LOTTERY = 'GET_CURRENT_SFC_LOTTERY';
export const SFC_CHANGE_ISSUE = 'SFC_CHANGE_ISSUE';
export const SFC_OPTION_SELECTED = 'SFC_OPTION_SELECTED';
export const SFC_BETTING_CONFIRM = 'SFC_BETTING_CONFIRM';
export const SFC_CALCULATOR_STACK = 'SFC_CALCULATOR_STACK';
export const SFC_CONFIRM_PAYMENT = 'SFC_CONFIRM_PAYMENT';
